package workproductcomponent

import "time"

// Fluid Efficiency Test for this pumping diagnostic session.
type StimFluidEfficiencyTest struct {
	// An analysis method used for this FET.                                                              
	AnalysisMethodID                                                                           *string    `json:"AnalysisMethodID,omitempty"`
	// End time for the FET.                                                                              
	EndDateTime                                                                                *time.Time `json:"EndDateTime,omitempty"`
	// A measurement, derived from a data frac, of the efficiency of a particular fluid in                
	// creating fracture area on a particular formation at a set of conditions.                           
	FluidEfficiency                                                                            *float64   `json:"FluidEfficiency,omitempty"`
	// The time required for the fracture to effectively close without proppant in place.                 
	FractureCloseDuration                                                                      *float64   `json:"FractureCloseDuration,omitempty"`
	// The pressure at which the fracture effectively closes without proppant in place.                   
	FractureClosePressure                                                                      *float64   `json:"FractureClosePressure,omitempty"`
	// The fracture pressure limit for an unfractured formation is the fracture initiation                
	// pressure. This is typically considered the upper bound for the minimum horizontal stress           
	// or closure pressure. A step-rate test is used to determine the fracture extension                  
	// pressure.                                                                                          
	FractureExtensionPressure                                                                  *float64   `json:"FractureExtensionPressure,omitempty"`
	// The fracture gradient of the formation.                                                            
	FractureGradient                                                                           *float64   `json:"FractureGradient,omitempty"`
	// The length of the fracture tip to tip; fracture half length is the length of one wing of           
	// a fracture from the wellbore to the tip.                                                           
	FractureLength                                                                             *float64   `json:"FractureLength,omitempty"`
	// The width of a fracture at the wellbore. Hydraulic frac width is generated by frac fluid           
	// viscosity andor pump rate (i.e., horsepower).                                                      
	FractureWidth                                                                              *float64   `json:"FractureWidth,omitempty"`
	// The difference between the fracture extension pressure and the pressure that exists in             
	// the fracture.                                                                                      
	NetPressure                                                                                *float64   `json:"NetPressure,omitempty"`
	// The pressure dependent leak-off coefficient.                                                       
	PdlCoefficient                                                                             *float64   `json:"PdlCoefficient,omitempty"`
	// The end of the pressure-dependent leak-off portion of the FET.                                     
	PdlEndDuration                                                                             *float64   `json:"PdlEndDuration,omitempty"`
	// The pressure of the liquids in the formation pore space.                                           
	PorePressure                                                                               *float64   `json:"PorePressure,omitempty"`
	// The Horner plot is used to determine if pseudo-radial flow developed during pressure               
	// decline. If a semi-log straight line is observed and the line can be extrapolated to a             
	// reasonable value of reservoir pressure, then radial or pseudo-radial flow may be                   
	// affecting the decline behavior. This suggests that the fracture is already closed and              
	// that data beyond the point of influence need not be considered in the evaluation of                
	// closure.                                                                                           
	PseudoRadialPressure                                                                       *float64   `json:"PseudoRadialPressure,omitempty"`
	// That permeability which remains after a fractured formation has closed, allowing the the           
	// formation fracture face to be pressurized before the fracture is mechanically reopened.            
	ResidualPermeability                                                                       *float64   `json:"ResidualPermeability,omitempty"`
	// Start time for the FET.                                                                            
	StartDateTime                                                                              *time.Time `json:"StartDateTime,omitempty"`
}
