package masterdata

// For a sample that has been recombined from separate samples, e.g. liquid sample and vapor
// sample, this object records the specified: recombination conditions (pressure and
// temperature), recombination ratio, the saturation pressure and  target recombined sample
// composition, whichever of these are appropriate for this recombination effort.
type RecombinationSpecification struct {
	// The prevailing operating conditions (Pressure and Temperature)  for the recombination                                      
	// operation.                                                                                                                 
	RecombinationCondition                                                                      AbstractPTCondition               `json:"RecombinationCondition"`
	// The gas-oil ratio recorded for this sample recombination process as well as the                                            
	// volumetric reference conditions for both the oil and gas phases. This is typically                                         
	// required for fluid sample types.                                                                                           
	RecombinationGasOilRatio                                                                    *RecombinationGasOilRatio         `json:"RecombinationGasOilRatio,omitempty"`
	// The observed saturation pressure for this sample recombination process. Mostly applies to                                  
	// fluid samples.                                                                                                             
	RecombinationSaturationPressure                                                             *float64                          `json:"RecombinationSaturationPressure,omitempty"`
	// Object capturing the mixture and contributions from multiple samples.                                                      
	RecombinedSampleFraction                                                                    []RecombinedSampleFractionElement `json:"RecombinedSampleFraction"`
	// Pertinent information about the sample recombination specification stored alongside the                                    
	// other attributes.                                                                                                          
	Remarks                                                                                     []AbstractRemark                  `json:"Remarks,omitempty"`
	// This provides an array of components and their fraction contribution to the overall                                        
	// expected composition of the  sample generated by the recombination process. This is                                        
	// typically required for fluid sample types.                                                                                 
	TargetSampleComposition                                                                     []TargetSampleCompositionElement  `json:"TargetSampleComposition,omitempty"`
}
