# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Generate schema models

on:
  workflow_dispatch:  
  schedule:
    - cron: 0 0 1 * *
  push:
    branches:
      - main
jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.13.1'

    - name: Install quicktype
      run: |
        npm install -g quicktype


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Run Go program
      run: go run .

    - name: Check for changes
      id: check_changes
      run: |
        # Check for any changes (added, modified, or deleted files)
        if [[ $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_ENV
        else
          echo "changes=false" >> $GITHUB_ENV
        fi

    - name: Create a new branch and push changes
      if: env.changes == 'true'
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |
        NEW_BRANCH="update-$(date +'%Y%m%d%H%M%S')"  # Unique branch name
        git checkout -b $NEW_BRANCH
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./* 
        git commit -m "Add new schemas"
        git push --set-upstream origin $NEW_BRANCH
        gh pr create -B main -H $NEW_BRANCH --title "Update schema files" --body "This PR updates the schema files generated by the Go program."
